name: Load Testing

on:
  workflow_dispatch:

jobs:

  load-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        
      - name: Azure Load Testing
        id: azure_load_testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: './JMeter/tealt-dev.yaml'
          loadTestResource: ${{ secrets.ALT_NAME }}
          resourceGroup: ${{ secrets.AZURE_RG }}
      - name: Save output
        if: failure()
        run: echo "${{ steps.azure_load_testing.outputs.result }}" > output.txt
      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('output.txt', 'utf8');
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Azure Load Testing failed",
              body: output
            };
            github.rest.issues.create(issue);